written = [
    "async_search.rs",
    "autoscaling.rs",
    "cat.rs",
    "ccr.rs",
    "cluster.rs",
    "connector.rs",
    "dangling_indices.rs",
    "enrich.rs",
    "eql.rs",
    "esql.rs",
    "features.rs",
    "fleet.rs",
    "graph.rs",
    "ilm.rs",
    "indices.rs",
    "inference.rs",
    "ingest.rs",
    "license.rs",
    "logstash.rs",
    "migration.rs",
    "ml.rs",
    "monitoring.rs",
    "nodes.rs",
    "profiling.rs",
    "query_rules.rs",
    "rollup.rs",
    "root/mod.rs",
    "search_application.rs",
    "searchable_snapshots.rs",
    "security.rs",
    "shutdown.rs",
    "simulate.rs",
    "slm.rs",
    "snapshot.rs",
    "sql.rs",
    "ssl.rs",
    "synonyms.rs",
    "tasks.rs",
    "text_structure.rs",
    "transform.rs",
    "watcher.rs",
    "xpack.rs",
]
merged = [
    "lib.rs",
    "params.rs",
]
